### ISSUE TITLE
Add the implementation of the "Ping request" telecommand

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/spacelab-transmitter#20]
As a first experiment with the telecommands, the "ping request" can be implemented. When the respective button is clicked, a ping request packet should be generated using the [PyNGHam](https://github.com/mgm8/pyngham) library.

**Tasks**:
- [x] Add a "clicked" event signal as a function
- [x] Initialize the main class of PyNGHam
- [x] Generate the payload of the "Ping Request" packet (ID + source callsign)
- [x] Generate the NGHam packet using the "encode" method
- [x] Generate a log event and print it on the event log treeview
- [x] Print the generated packet (temporary, just until we add the communication with the SDR)
